# Generated by Django 5.0.4 on 2024-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_city_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.product'),
        ),
    ]
