# Generated by Django 5.0.4 on 2024-04-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_telegramuser_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shop.city', verbose_name='City'),
        ),
    ]
