# Generated by Django 5.0.4 on 2024-04-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_quantity_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, verbose_name='Address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='City', to='shop.city')),
            ],
        ),
    ]
