# Generated by Django 5.0.4 on 2024-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shop_options_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount',
            options={'verbose_name': 'Amount', 'verbose_name_plural': 'Amounts'},
        ),
        migrations.AddConstraint(
            model_name='amount',
            constraint=models.UniqueConstraint(fields=('product', 'shop'), name='unique_product_shop'),
        ),
        migrations.AlterModelTable(
            name='amount',
            table='amounts',
        ),
    ]
