# Generated by Django 5.0.4 on 2024-04-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_amount_options_amount_unique_product_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='related_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shop.shop', verbose_name='Shop'),
        ),
    ]
