# Generated by Django 5.0.4 on 2024-05-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_telegramuser_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
    ]
