# Generated by Django 5.0.4 on 2024-05-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
