# Generated by Django 5.0.4 on 2024-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_telegramuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
